name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - name: Build and Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # ビルドディレクトリの作成
          mkdir -p build
          # クライアントファイルのコピー
          cp index.html styles.css script.js build/
          # プロキシサーバーの起動
          node server.js &
          # デプロイ
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push origin main
        force_orphan: true
